// This file is auto-generated by scripts/export_contracts.py. Do not edit manually.

export interface Article {
  id: string;
  title: string;
  url: string;
  published: string;
  source_name: string;
  source_category: 'arxiv' | 'news' | 'official' | 'community';
  summary_zh: string;
  tags: Array<string>;
  importance: number;
}

export interface DigestStats {
  total: number;
  by_category: Record<string, number>;
  by_tag: Record<string, number>;
}

export interface DigestResponse {
  date: string;
  generated_at: string;
  stats: DigestStats;
  articles: Array<Article>;
}

export interface DateEntry {
  date: string;
  total: number;
  by_category: Record<string, number>;
}

export interface DateListResponse {
  dates: Array<DateEntry>;
  latest: string | null;
}

export interface DigestQueryParams {
  tags?: Array<string>;
  category?: string | null;
  min_importance?: number;
  sort?: 'importance' | 'published';
  q?: string | null;
}

export interface PipelineRunResponse {
  status: 'started';
}

export interface PipelineProgressResponse {
  stage: 'starting' | 'fetching' | 'stage1' | 'stage2' | 'finalizing' | 'completed' | 'error' | null;
  message: string | null;
  current: number | null;
  total: number | null;
  candidates: number | null;
  selected: number | null;
  processed: number | null;
  report_articles: number | null;
}

export interface PipelineStatusResponse {
  running: boolean;
  last_run: string | null;
  error: string | null;
  last_outcome: 'success' | 'no_new_items' | 'error' | null;
  progress: PipelineProgressResponse | null;
}

export interface GitHubProject {
  id: string;
  full_name: string;
  description?: string | null;
  description_zh?: string | null;
  html_url: string;
  homepage?: string | null;
  stars: number;
  forks: number;
  open_issues: number;
  language?: string | null;
  topics: Array<string>;
  category: 'llm' | 'agent' | 'cv' | 'nlp' | 'ml_framework' | 'mlops' | 'general';
  created_at?: string | null;
  updated_at?: string | null;
  pushed_at?: string | null;
  owner_avatar?: string | null;
  owner_type?: string | null;
  license?: string | null;
  stars_today?: number | null;
  stars_weekly?: number | null;
  trend?: 'hot' | 'rising' | 'stable' | null;
}

export interface GitHubTrendingStats {
  total: number;
  by_category: Record<string, number>;
  by_language: Record<string, number>;
}

export interface GitHubTrendingResponse {
  date: string;
  generated_at: string;
  stats: GitHubTrendingStats;
  projects: Array<GitHubProject>;
}

export interface GitHubFetchResult {
  outcome: 'success' | 'degraded';
  reason?: 'missing_token' | 'rate_limit' | null;
  snapshot?: GitHubTrendingResponse | null;
  partial_path?: string | null;
}

export interface GitHubDateListResponse {
  dates: Array<string>;
  latest?: string | null;
}

export interface GitHubQueryParams {
  category?: string | null;
  language?: Array<string> | string | null;
  min_stars?: number;
  sort?: 'stars' | 'stars_today' | 'stars_weekly' | 'updated';
  q?: string | null;
  trend?: 'hot' | 'rising' | 'stable' | null;
}

export interface GitHubFetchRunResponse {
  status: 'started';
}

export interface GitHubFetchProgressResponse {
  stage: 'starting' | 'searching' | 'deduplicating' | 'computing_trends' | 'saving' | 'completed' | 'error' | null;
  message: string | null;
  current: number | null;
  total: number | null;
  topics_done: number | null;
  topics_total: number | null;
  projects_found: number | null;
  projects_new: number | null;
}

export interface GitHubFetchStatusResponse {
  running: boolean;
  last_run: string | null;
  error: string | null;
  last_outcome: 'success' | 'degraded' | 'error' | null;
  progress: GitHubFetchProgressResponse | null;
}

export interface LlmProviderSettings {
  base_url?: string;
  model?: string;
  temperature?: number;
  max_tokens?: number;
}

export interface LlmSettings {
  provider?: 'siliconflow' | 'newapi';
  siliconflow?: LlmProviderSettings;
  newapi?: LlmProviderSettings;
}

export interface PipelineSettings {
  time_window_hours?: number;
  max_articles_per_day?: number;
  max_articles_to_stage2?: number;
  stage1_batch_size?: number;
}

export interface GitHubTrendingSettings {
  enabled?: boolean;
  min_stars?: number;
  max_projects_per_day?: number;
}

export interface DesktopSettingsSnapshot {
  timezone?: string;
  llm?: LlmSettings;
  pipeline?: PipelineSettings;
  github_trending?: GitHubTrendingSettings;
  llm_api_key?: string;
  github_token?: string;
}

export interface ValidationIssue {
  field?: string | null;
  message: string;
}

export interface ValidationResult {
  valid: boolean;
  issues?: Array<ValidationIssue>;
}

export type DailyDigest = DigestResponse;
export type DateList = DateListResponse;
export type QueryParams = DigestQueryParams;
export type PipelineProgress = PipelineProgressResponse;
export type PipelineStatus = PipelineStatusResponse;
export type GitHubTrendingData = GitHubTrendingResponse;
export type GitHubFetchProgress = GitHubFetchProgressResponse;
export type GitHubFetchStatus = GitHubFetchStatusResponse;
