import json
from collections import OrderedDict
from pathlib import Path
from typing import Any

from .registry import CONTRACT_DEFINITIONS, FRONTEND_COMPAT_ALIASES

AUTOGENERATED_NOTICE = "// This file is auto-generated by scripts/export_contracts.py. Do not edit manually."
SCHEMA_FILENAME = "contracts.schema.json"
TYPES_FILENAME = "index.ts"


def build_contract_schema_bundle() -> dict[str, Any]:
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "AIDailyContractBundle",
        "models": OrderedDict(
            (definition.name, definition.model.model_json_schema()) for definition in CONTRACT_DEFINITIONS
        ),
        "frontend_aliases": OrderedDict(FRONTEND_COMPAT_ALIASES.items()),
    }


def build_contract_schema_json() -> str:
    return json.dumps(build_contract_schema_bundle(), indent=2, ensure_ascii=False) + "\n"


def build_frontend_typescript() -> str:
    sections = [AUTOGENERATED_NOTICE, ""]
    for definition in CONTRACT_DEFINITIONS:
        sections.append(_render_interface(definition.name, definition.model.model_json_schema()))
        sections.append("")

    for alias, target in FRONTEND_COMPAT_ALIASES.items():
        sections.append(f"export type {alias} = {target};")

    return "\n".join(section.rstrip() for section in sections).rstrip() + "\n"


def get_artifact_paths(repo_root: Path) -> dict[Path, str]:
    types_dir = repo_root / "frontend" / "src" / "types"
    return {
        types_dir / TYPES_FILENAME: build_frontend_typescript(),
        types_dir / SCHEMA_FILENAME: build_contract_schema_json(),
    }


def write_artifacts(repo_root: Path) -> list[Path]:
    written: list[Path] = []
    for path, content in get_artifact_paths(repo_root).items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


def check_artifacts(repo_root: Path) -> list[Path]:
    stale: list[Path] = []
    for path, content in get_artifact_paths(repo_root).items():
        existing = path.read_text(encoding="utf-8") if path.exists() else None
        if existing != content:
            stale.append(path)
    return stale


def _render_interface(name: str, schema: dict[str, Any]) -> str:
    required = set(schema.get("required", []))
    properties = schema.get("properties", {})
    lines = [f"export interface {name} {{"]
    for property_name, property_schema in properties.items():
        optional = "?" if property_name not in required else ""
        lines.append(f"  {property_name}{optional}: {_render_type(property_schema)};")
    lines.append("}")
    return "\n".join(lines)


def _render_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", maxsplit=1)[-1]

    if "anyOf" in schema:
        parts = [_render_type(part) for part in schema["anyOf"]]
        return " | ".join(_dedupe(parts))

    if "enum" in schema:
        return " | ".join(_render_literal(value) for value in schema["enum"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(_dedupe(_render_type({"type": item}) for item in schema_type))

    if schema_type == "string":
        return "string"
    if schema_type == "integer" or schema_type == "number":
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        item_type = _render_type(schema.get("items", {}))
        return f"Array<{item_type}>"
    if schema_type == "object":
        if "additionalProperties" in schema:
            return f"Record<string, {_render_type(schema['additionalProperties'])}>"
        if "properties" in schema:
            required = set(schema.get("required", []))
            chunks = []
            for property_name, property_schema in schema["properties"].items():
                optional = "?" if property_name not in required else ""
                chunks.append(f"{property_name}{optional}: {_render_type(property_schema)}")
            return "{ " + "; ".join(chunks) + " }"
        return "Record<string, unknown>"

    return "unknown"


def _render_literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace("'", "\\'")
        return f"'{escaped}'"
    return json.dumps(value, ensure_ascii=False)


def _dedupe(values: list[str] | tuple[str, ...] | Any) -> list[str]:
    ordered: list[str] = []
    for value in values:
        if value not in ordered:
            ordered.append(value)
    return ordered
